# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - id: "pop1"
    binary: pop-amd64-linux
    main: "./cmd/pop"
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
  - id: "pop2"
    binary: pop-arm64-linux
    main: "./cmd/pop"
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - arm64
  - id: "pop3"
    binary: pop-amd64-darwin
    main: "./cmd/pop"
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
  - id: "pop4"
    binary: pop-arm64-darwin
    main: "./cmd/pop"
    env:
      - CGO_ENABLED=1
      - CC=aarch64-apple-darwin20.2-clang
      - CXX=aarch64-apple-darwin20.2-clang++
    goos:
      - darwin
    goarch:
      - arm64
archives:
  - format: binary
  # - replacements:
  #     darwin: Darwin
  #     linux: Linux
  #     windows: Windows
  #     386: i386
  #     amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
