apiVersion: apps/v1
kind: Deployment
metadata:
  name: pop-deployment
  labels:
    app: pop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pop
  template:
    metadata:
      labels:
        app: pop
    spec:
      containers:
      - name: pop
        image: ${REGISTRY_URL}:latest
        ports:
        - containerPort: 2001
