[metadata]
  name = "high_content_replication"

[global]
  plan = "testplans"
  case = "routing_gossip"
  total_instances = 40
  builder = "docker:go"
  runner = "cluster:k8s"

[global.run.test_params]
  regions = '["Global"]'
  bootstrap = "10"
  providers = "8"

[[groups]]
  id = "bystanders"
    [groups.instances]
    count = 31

[[groups]]
  id = "providers"
   [groups.instances]
    count = 8

[[groups]]
  id = "clients"
  [groups.instances]
    count = 1

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="https://proxy.golang.org"
  registry_type="aws"
