[metadata]
  name = "sequential_groups"

[global]
  plan = "testplans"
  case = "replication_bootstrap"
  total_instances = 10
  builder = "docker:go"
  runner = "cluster:k8s"

[global.run.test_params]
  regions = '["Global"]'
  bootstrap = "4"
  providers_1 = "5"
  providers_2 = "5"
  tx_per_provider = "5"

[global.build_config]
  push_registry=true
  go_proxy_mode="remote"
  go_proxy_url="https://proxy.golang.org"
  registry_type="aws"

[[groups]]
  id = "providers_1"
  [groups.instances]
    count = 5

[[groups]]
  id = "providers_2"
  [groups.instances]
    count = 5
