name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Sync Submodule
      run: |
        git submodule sync
        git submodule update --init

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Linux deps
      run: |
        sudo apt-get update
        sudo apt-get install ocl-icd-opencl-dev hwloc libhwloc-dev

    - name: Test
      run: go test -v ./...
