---
name: "tagged-prerelease"

on:
  push:
    tags:
      - "*-rc*"
  workflow_dispatch:

jobs:
  tagged-prerelease:
    name: "Tagged Prerelease"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: "Build Binaries"
        run: make snapshot
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "${{ steps.vars.outputs.tag }}"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            ./dist/pop*/pop*
